library(markdown)
library(Quandl)
library(shiny)
require(rCharts)
library(shinyBS)
library(DT)
library(googleVis)
library(shinythemes)
library(shinydashboard)
load("shocks.RData")
options(RCHART_LIB = 'highcharts')
ui <- dashboardPage(
  dashboardHeader(title = "Stress Testing Tool"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Explore MacroEconomic Data", tabName = "macro", icon = icon("dashboard")),
      menuItem("Simulation: Core Variables", icon = icon("support"), tabName = "simcore",badgeLabel = "V2", badgeColor = "green"),
      menuItem("Simulation: Non Core Variables", icon = icon("bar-chart"), tabName = "simnoncore",badgeLabel = "V2", badgeColor = "red"),
      menuItem("Forecast Model", icon = icon("bar-chart"), tabName = "fore",badgeLabel = "V2", badgeColor = "yellow"),
      menuItem("User Guides", icon = icon("bar-chart"), tabName = "uguide",badgeLabel = "V2", badgeColor = "yellow")
    )
  ),
  dashboardBody(
    tags$head(
      tags$link(rel = "stylesheet", type = "text/css", href = "style.css")
    ),
    tabItems(
      tabItem(tabName = "macro",
              box(title = "Exploration Options", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h4("Get the codes for data series from https://www.quandl.com/search?type=all. (Free Section Only)"),
                  h3("Input Section"),
                  textInput("dataseries", "Enter Data Name:", "FRED/NGDPPOT,FRED/NROUST"),
                  bsTooltip("dataseries", "Enter multiple values separated by commas only (No Quotes)", options = list(container = "body")),
                  selectInput("transform", "Get Transformation", choices=c("NULL", "diff", "rdiff", "normalize", "cumul", "rdiff_from"),selected = "NULL"),
                  bsTooltip("transform", "Use transform=none|diff|rdiff|cumul|normalize to get changes, % changes, cumulative sums, or returns from 100 ", options = list(container = "body")),
                  selectInput("frequency", "Get Frequency", choices=c("NULL", "daily", "weekly", "monthly", "quarterly", "annual"),selected = "NULL"),
                  h3("View Metadata"),
                  uiOutput('Descselect'),
                  bsTooltip("Descselect", "Select series in dropdown for which metatda is to be viewed", options = list(container = "body")),
                  h3("Download History File"),
                  selectInput('Format', "Select Format", choices=c('csv','xls')),
                  downloadButton('downloadData1', 'Download')),
              box(title = "Charts and Description", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h3("Time Series Plot of Macro Economic Series"),
                  tabPanel("Charts", showOutput("chart1", "highcharts")),
                  h3("Data Description of Macro Economic Series"),
                  tableOutput('desctab'))
      ),
      tabItem(tabName = "simcore",
              box(title = "Report Options", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h4("Get the codes for data series from https://www.quandl.com/search?type=all. (Free Section Only)"),
                  h3("Input Section: Choose Core Variables"),
                  checkboxInput("core1", "Real GDP growth", value = FALSE, width = NULL),
                  checkboxInput("core2", "Real Consumption growth", value = FALSE, width = NULL),
                  checkboxInput("core3", "Real Investment growth", value = FALSE, width = NULL),
                  checkboxInput("core4", "Aggregate Hours", value = FALSE, width = NULL),
                  checkboxInput("core5", "Core PCE Inflation", value = FALSE, width = NULL),
                  checkboxInput("core6", "Fed funds rate", value = FALSE, width = NULL),
                  selectInput("shock_var", "Choose a variable to shock by",choices = c("Preference", "Labour supply", "Investment", "Productivity","Wage markup", "Price markup", "Government spending", "Interest rates","Inflation objective")),
                  conditionalPanel("input.shock_var == 'Preference'",
                                   sliderInput("eta_b", "Preference shock", 0, 0.75, shocks[1, "value"])),
                  conditionalPanel("input.shock_var == 'Labour supply'",
                                   sliderInput("eta_L", "Labour supply shock", 0, 7, step = 0.01, shocks[2, "value"])),
                  conditionalPanel("input.shock_var == 'Investment'",
                                   sliderInput("eta_I", "Investment shock", 0, 0.2, shocks[3, "value"])),
                  conditionalPanel("input.shock_var == 'Productivity'",      
                                   sliderInput("eta_a", "Productivity shock", 0, 1.2, shocks[4, "value"])),
                  conditionalPanel("input.shock_var == 'Wage markup'",      
                                   sliderInput("eta_w", "Wage markup shock", 0, 1.4, shocks[5, "value"])),
                  conditionalPanel("input.shock_var == 'Price markup'",      
                                   sliderInput("eta_p", "Price markup shock", 0, 1.6, shocks[6, "value"])),
                  conditionalPanel("input.shock_var == 'Government spending'",      
                                   sliderInput("eta_G", "Government spending shock", 0, 0.75, shocks[7, "value"])),
                  conditionalPanel("input.shock_var == 'Interest rates'",      
                                   sliderInput("eta_R", "Interest rates shock", 0, 0.2, shocks[8, "value"])),
                  conditionalPanel("input.shock_var == 'Inflation objective'",      
                                   sliderInput("eta_pi", "Inflation objective shock", 0, 0.05, shocks[9, "value"])),
                  h4('Enter Simulation & Forecast Details'),
                  textInput("forecount", "Enter perios to Forecast:", "14"),
                  bsTooltip("forecount", "Enter Periods to forecast", options = list(container = "body")),
                  textInput("simcount", "Enter Simulation Count:", "100"),
                  bsTooltip("simcount", "Enter number of simulations to create", options = list(container = "body")),
                  actionButton("Simulate", "Run_Simulation", width = "100%"),
                  selectInput('Formatcoresim', "Select Format", choices=c('csv','xls')),
                  downloadButton('downloadSimData', 'Download Simulation'),
                  h3("View Simulations"),
                  uiOutput('corevarselect'),
                  uiOutput('coreperselect'),
                  selectInput("frequencycore", "Get Frequency", choices=c("NULL", "daily", "weekly", "monthly", "quarterly", "annual"),selected = "NULL"),
                  h3("Change Initial Parameters"),
                  checkboxInput("inchng", "Change Initial Parameters?", value = FALSE, width = NULL),
                  conditionalPanel("input.inchng == true",
                                   actionButton("goButton", "Redraw With Fresh Initialisation", width = "100%"),
                                   h4("Consumer"),
                                   sliderInput("beta", "Discount factor", 0.9, 0.999, 0.99),
                                   sliderInput("tau", "Capital depreciation rate", 0, 0.1, 0.025),
                                   sliderInput("varphi", "Investment adjustment cost", 2, 13, 6.771),
                                   sliderInput("psi", "Capacity utilisation cost", 0.05, 0.3, 0.169),
                                   sliderInput("sigma_c", "Relative risk aversion", 0.9, 2, 1.353),
                                   sliderInput("h", "Habit formation intensity", 0.3, 1, 0.573),
                                   sliderInput("sigma_l_inv", "Labour elasticity wrt wage", 0.1, 0.9, 1 / 2.4),
                                   sliderInput("omega", "Labour disutility", 0.5, 1.5, 1),
                                   h4("Other"),
                                   sliderInput("alpha", "Capital share in output", 0, 0.9, step = 0.01, 0.3),
                                   sliderInput("gamma_w", "Indexation for non-optimising workers", 0, 1, step = 0.001, 0.763),
                                   sliderInput("lambda_w", "Wage markup", 0.3, 0.7, step = 0.001, 0.5),
                                   sliderInput("xi_w", "Probability of missing wage-change signal", 0.6, 1, step = 0.001, 0.737),
                                   sliderInput("gamma_p", "Indexation for non-optimising firms", 0, 1, step = 0.001, 0.469),
                                   sliderInput("xi_p", "Probability of missing price-change signal", 0.6, 1, step = 0.001, 0.908),
                                   sliderInput("r_pi", "Weight given by monetary authority to inflation", 0, 3, step = 0.001, 1.684))),
              box(title = "Charts and Results", status = "primary", 
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h3("IRF for Smets Wouters Model"),
                  tabPanel("irfplot", showOutput("chart5", "highcharts")),
                  verbatimTextOutput("nText"),
                  h3("Histogram and Stats of simulation"),
                  htmlOutput("coreDist"),
                  tableOutput('corestats'))
      ),
      tabItem(tabName = "simnoncore",
              tags$head(tags$style(".leftAlign{float:left;}")),
              box(title = "Report Options", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h4("Get the codes for data series from https://www.quandl.com/search?type=all. (Free Section Only)"),
                  h3("Input Section"),
                  textInput("dataseriessim", "Enter Data Name:", "FRED/NGDPPOT,FRED/NROUST"),
                  bsTooltip("dataseriessim", "Enter multiple values separated by commas only (No Quotes)", options = list(container = "body")),
                  selectInput("simmet", "Choose Simulation Method", choices=c("Univariate Method", "Fed Method"),selected = "Univariate Method"),
                  conditionalPanel("input.simmet == 'Fed Method'",
                                   checkboxInput("Simcorenc1", "Real GDP growth", value = FALSE, width = NULL),
                                   textInput("Simcorenc1var", "Enter Data Name:", "FRED/GDP"),
                                   checkboxInput("Simcorenc2", "Real Consumption growth", value = FALSE, width = NULL),
                                   textInput("Simcorenc2var", "Enter Data Name:", "FRED/PCECC96"),
                                   checkboxInput("Simcorenc3", "Real Investment growth", value = FALSE, width = NULL),
                                   textInput("Simcorenc3var", "Enter Data Name:", "FRED/RINV"),
                                   checkboxInput("Simcorenc4", "Aggregate Hours", value = FALSE, width = NULL),
                                   textInput("Simcorenc4var", "Enter Data Name:", "FRED/LNU01000000"),
                                   checkboxInput("Simcorenc5", "Core PCE Inflation", value = FALSE, width = NULL),
                                   textInput("Simcorenc5var", "Enter Data Name:", "RATEINF/INFLATION_USA"),
                                   checkboxInput("Simcorenc6", "Fed funds rate", value = FALSE, width = NULL),
                                   textInput("Simcorenc6var", "Enter Data Name:", "PERTH/FEDF_M")),
                  selectInput("transformsim", "Get Transformation", choices=c("NULL", "diff", "rdiff", "normalize", "cumul", "rdiff_from"),selected = "NULL"),
                  bsTooltip("transformsim", "Use transform=none|diff|rdiff|cumul|normalize to get changes, % changes, cumulative sums, or returns from 100 ", options = list(container = "body")),
                  selectInput("frequencysim", "Get Frequency", choices=c("NULL", "daily", "weekly", "monthly", "quarterly", "annual"),selected = "NULL"),
                  textInput("signind", "Enter Signs for Outlook:", "+,+"),
                  bsTooltip("signind", "Enter + if increase in variable signifies better outlook e.g. GDP, enter - if variable increase suggests worse outlook e.g. umployment. Separate signs by commas", options = list(container = "body")),
                  selectInput("simoutlook", "Choose Outlook", choices=c("Very Positive", "Positive", "Neutral", "Negative", "Very Negative"),selected = "NULL"),
                  h3("Select Plot & DataTable View"),
                  uiOutput('Varselect'),
                  bsTooltip("Varselect", "Select Simulation Variable to see", options = list(container = "body")),
                  selectInput("view", "Choose Table View", choices=c("Simulation","Forecast"),selected = "NULL"),
                  h3("Select Distribution View"),
                  uiOutput('varsimselect'),
                  uiOutput('perselect'),
                  h3("Download Simulation File"),
                  uiOutput('Varsimselect'),
                  selectInput('Formatsim', "Select Format", choices=c('csv','xls')),
                  downloadButton('downloadData2', 'Download')),
              box(title = "Charts and Results", status = "primary", 
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  class = 'leftAlign',
                  h3("Forecast and Outlook Chart"),
                  tabPanel("ForecastChart", showOutput("chart2", "highcharts")),
                  h3("Simulation Table of Macro Economic Series"),
                  tabPanel("simtabview", DT::dataTableOutput('simtab')),
                  h3("Single Period Histogram and Descriptives of Simulation"),
                  tabPanel("gvishist", htmlOutput("Dist")),
                  tableOutput('noncorestats'))
      ),
      tabItem(tabName = "fore",
              box(title = "Report Options", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h4("Get the codes for data series from https://www.quandl.com/search?type=all. (Free Section Only)"),
                  h3("Input Section for Dependant Variable"),
                  checkboxGroupInput("depvarchc", "Input Variable or upload:",c("Input","Upload")),
                  conditionalPanel(
                    condition = "input.depvarchc == 'Input'",
                    textInput("depvar", "Enter Data Name:", "FRED/NROUST"),
                    bsTooltip("dataseriessim", "Enter multiple values separated by commas only (No Quotes)", options = list(container = "body"))
                  ),
                  conditionalPanel(
                    condition = "input.depvarchc == 'Upload'",
                    fileInput('depvarfile', 'Choose file to upload',accept = c('text/csv','text/comma-separated-values','text/tab-separated-values','text/plain','.csv','.tsv')),
                    bsTooltip("depvarfile", "Only one column data, rows should equal no of data points for macro IV variables", options = list(container = "body")),
                    checkboxInput('header', 'Header', TRUE),
                    radioButtons('sep', 'Separator',
                                 c(Comma=',',
                                   Semicolon=';',
                                   Tab='\t'),
                                 ','),
                    radioButtons('quote', 'Quote',
                                 c(None='',
                                   'Double Quote'='"',
                                   'Single Quote'="'"),
                                 '"')
                  ),
                  h3("Input Section for InDependant Variable"),
                  h4("Select Core Variables"),
                  checkboxInput("Fcore1", "Real GDP growth", value = FALSE, width = NULL),
                  textInput("Fcore1var", "Enter Data Name:", "FRED/GDP"),
                  checkboxInput("Fcore2", "Real Consumption growth", value = FALSE, width = NULL),
                  textInput("Fcore2var", "Enter Data Name:", "FRED/PCECC96"),
                  checkboxInput("Fcore3", "Real Investment growth", value = FALSE, width = NULL),
                  textInput("Fcore3var", "Enter Data Name:", "FRED/RINV"),
                  checkboxInput("Fcore4", "Aggregate Hours", value = FALSE, width = NULL),
                  textInput("Fcore4var", "Enter Data Name:", "FRED/LNU01000000"),
                  checkboxInput("Fcore5", "Core PCE Inflation", value = FALSE, width = NULL),
                  textInput("Fcore5var", "Enter Data Name:", "RATEINF/INFLATION_USA"),
                  checkboxInput("Fcore6", "Fed funds rate", value = FALSE, width = NULL),
                  textInput("Fcore6var", "Enter Data Name:", "PERTH/FEDF_M"),
                  sliderInput("control", "Choose Simulation:", min=0, max=1000, value=10,step=1),
                  h4("Select Non Core Variables"),
                  textInput("foreseriessim", "Enter Data Name:", "FRED/NROU,FRED/B060RC0A144NBEA"),
                  bsTooltip("foreseriessim", "Enter single series only (No Quotes)", options = list(container = "body")),
                  selectInput("transformfore", "Get Transformation", choices=c("NULL", "diff", "rdiff", "normalize", "cumul", "rdiff_from"),selected = "NULL"),
                  bsTooltip("transformfore", "Use transform=none|diff|rdiff|cumul|normalize to get changes, % changes, cumulative sums, or returns from 100 ", options = list(container = "body")),
                  selectInput("frequencyfore", "Get Frequency", choices=c("NULL", "daily", "weekly", "monthly", "quarterly", "annual"),selected = "NULL"),
                  textInput("signfore", "Enter Signs for Outlook:", "+,+"),
                  selectInput("foreoutlook", "Choose Outlook", choices=c("Very Positive", "Positive", "Neutral", "Negative", "Very Negative"),selected = "NULL"),
                  actionButton("do", "Remove all Previous fits")),
              box(title = "Charts and Results", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  h3("Independant Variable Table for ARIMA Model"),
                  tabPanel("IVTab",DT::dataTableOutput('IVTABLE')),
                  h3("Fitted Plot of ARIMA Model"),
                  tabPanel("Forecastfit", showOutput("chart3", "highcharts"),h4("Model Summary"),verbatimTextOutput("plotsummary")),
                  h3("Forecasted Plot of Metric"),
                  tabPanel("Forecastplot", showOutput("chart4", "highcharts")))
      ),
      tabItem(tabName = "uguide",
              box(title = "1. Report Options", status = "primary",
                  solidHeader = TRUE,width = 12,
                  collapsible = TRUE,
                  
                  tabsetPanel(
                    # using iframe along with tags() within tab to display pdf with scroll, height and width could be adjusted
                    tabPanel("Reference",tags$iframe(src="Manual.pdf", width="900", height="600"))
                  ))
      )
    )
  )
)